### ISSUE TITLE
website performance improvement checklist

### ISSUE THREAD

**Issue by scd** [theCrag/website#1166]
Check list of things we can do to improve system performance.
- [x] review join order in leaderboard queries 
- [x] use a replication server for facet and leaderboard (NOT DOING)
- [x] apache config: turn MaxRequestsPerChild up.
- [x] new server, properly dimension mysql in this server.
- [x] investigate star schema model options for leaderboard
- [x] investigate adding an account node table to statistics module for leaderboard searches
- [x] investigate nested set/intervals method for ascent/activity/route facet search. 
- [x] reduce number of mysql queries - monitor.
- [ ] refactor some generic tables (eg category) as single mysql query stored in memcached. 
- [ ] refactor login access code - uses too many small mysql queries
- [ ] refactor process code to change category mysql queries to memcached
- [ ] refactor node and account caches to be for a group of nodes to minimise sql queries
- [ ] reduce mod_perl memory footprint in apache, which will allow us to increase the number of apache servers.
- [ ] monitor memory creep from application data in mod_perl. Develop a mechanism to identify and monitor all caches so we can make a educated judgment on whether they should be memory resident or not.
- [ ] remove all instances of CGI.pm as it is a memory hog.
- [ ] replace some automatically generated perl state modules with memcached structures
- [ ] investigate ways of removing automatically generated table wrapper modules as they use a lot of memory. Maybe a massive piece of work.
- [ ] Enable read-only replication servers for api calls
- [x] Serve images from static

References:
http://en.wikipedia.org/wiki/Nested_set_model
http://en.wikipedia.org/wiki/Nested_intervals

**Comment by scd** [comment]
Closing because this is dealt with internally.
