### ISSUE TITLE
Task list of improvements to statistics package

### ISSUE THREAD

**Issue by scd** [theCrag/website#1189]
- [x] Add account node rollups
- [ ] Monitor errors
- [ ] Ensure business logic implemented consistently between dimensions and baseline/delta mode.
- [ ] Consolidate baseline code to fewer big mysql queries.
- [ ] Purge descendent records as this mechanism is no longer being used
- [ ] Tidy up config code to remove references to descendent records.

**Comment by scd** [comment]
Will deal with this internally. We do not need a public issue for this
