### ISSUE TITLE
topos associated with world area

### ISSUE THREAD

**Issue by scd** [theCrag/website#1201]
- [ ] Investigate whether this is because of the automated lowest common parent algorithm when moving a route to test area.
- [ ] Get Campbell (and the rest of us) to check before we move routes, until this problem is fixed.
- [ ] Assess whether or not we still want the automated LCP algorithm.
- [ ] Exclude world node from any automated LCP assignment.
- [ ] Add a warning to reparenting routes across world area.
- [ ] Assess existing topos for associated with world area - do they need moving back.

**Comment by rouletout** [comment]
This is not an issue anymore, closing
