### ISSUE TITLE
Make country contexts easy to visualise and data cleanup

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1216]
You guys seen the question on FB about default country contexts?

I've responded but maybe you guys should pitch in. One thing that became apparent to me is that it's a pain to easily see whats going on in the system. So to fix this I've revamped the context table in the help article to show the context better and also link to each country and displayed it all on a world map:

http://dev.thecrag.com/article/Grades#s6

Much clearer! But it highlights a lot of data issues:
- [x] South Africa context should be used for South Africa, as well as Lesotho, Botswana, Namibia, 
- [x] The Montenegro node isn't of type country, is out of order and is missing data?
- [x] New zealand should be AU

These are not linked to their nodes: (remove these they are not countries) - see issue #1566
- [ ] England
- [ ] Wales
- [ ] Scotland
- [ ] Northern Ireland
- [x] Most SE asian countries should be FR specifically: malaysia, singapore, laos, vietnam, malaysia, hong kong, 
- [x] Most US euro countries should be FR instead of US: specifically Netherlands, Portugal, Luxemburg, turkey, greece, italy, slovenia, croatia, monaco, andorra, sweden, Morocco, egypt, Kyrgyzstan, 
- [x] malta I'm pretty sure should be UK context
- [x] all central american countries stay as US, do nothing
- [ ] brazil has a grading system which looks like a fork from French which has diverged, similar to how south african diverged from australian. See #1139. This needs a whole new system, plus a whole new country context for brazil. Making matters worse it looks like they use the font 5A system for bouldering as well as the V grade. brazil is quite a mess, but with only 420 routes it's not a mess at scale and we should try to get things right here before the data grows too much more - see #1567
- [ ] some south american countries should be use either the Brazilian grades or French grade, specifically: argentina, peru, but the waters are muddy because those two systems / contexts overlap - see #1567
- [ ] remove tibet as a country - see issue #1566
- [x] most northern asian countries should remain US: china, japan, taiwan. china is a mess of AU and US grade's. Do nothing
- [ ] SAXON doesn't appear in the table anywhere, use it for germany? or investigate setting at region level, OR investigate making this context be used at german level and then adding other parseContexts to this context to make it work for germany, similar to the UIAA parseContext - see #1568
