### ISSUE TITLE
Forums checklist

### ISSUE THREAD

**Issue by scd** [theCrag/website#1260]
Collector issue for easy forum issues:
- [x] renaming Chat to Forums
- [x] header notification for unread discussions you are involved in.
- [x] header notification for unread forums you are watching.
- [ ] easily starting a crag forum discussion from list view
- [ ] email notification linking to private discussion when not logged in
- [x] responsive discussions
- [x] mobile friendly adding comments to discussions
- [x] navigation back to dashboard/forum from a discussion
- [x] "mark all as read" option on dashboard
- [x] test forum when not logged in - in particular behavior of read flag
- [x] more comments indicator appearing when it should not if you are not logged in.
