### ISSUE TITLE
Checklist of enhancements to rapportive

### ISSUE THREAD

**Issue by scd** [theCrag/website#1334]
Also see issue #1333 
- [ ] admin fields versus standard user fields
- [ ] social links (ie following, followed, follow action)
- [ ] full contact (admin)
- [x] total donations, as well as last (admin)
- [ ] hardest climb and style for standard user
- [x] sponsor flag for standard user
- [ ] how to article
- [ ] promote this workflow as a who's who of climbing.

**Comment by brendanheywood** [comment]
defunkt :(
