### ISSUE TITLE
Gym offline app checklist

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1353]
End game: scan QR code of rope A, get served whole gym contents, then scan rope B and don't go to network at all.

IF we are forced to add each rope into the manifest cache it means when you hit any rope, it will try to download every rope which is pretty gross. This may mean I have to use a #fragmentidenitifer instead of a /subpath which means we're not using the same url's as so we'll have to reprint the QR code's. 
- [ ] New template to render Manifest file serve
- [ ] set expires headers on manifest to something small. If we are pushing all data into localstorage this could be an hour or day, if not this should be very small or 0
- [ ] manifest template data, gym node data, plus all topos anywhere inside gym (could be two nodes deep and not linked or parented at gym node)
- [ ] manifest contains static versioned urls topo.js and new gym.js
- [ ] also contains links to all topo image refs
- [ ] urls to artwork like gym avatar
- [ ] sprite for ticks
- [ ] api calls to NETWORK
- [ ] avatar links to FALLBACK
- [ ] every rope area url  FALLBACK to gym node (need to test, does it try to make a 'master' resource first?)
- [ ] zero personal data in templates, 100% pulled from api
- [ ] probably new dedicated api call to grab latest tick data for un-archived routes
- [ ] combine all api calls into single call if possible - maybe? need to hash out login flow stuff
- [ ] probably a new api call to grab logged in status, falls back to offline url - this needs some more thought. store last logged in user in localstorage
- [ ] do we store old ticks in localstorage? yeah key by route id should be easy, do we want to be able to search?
- [ ] future, 100% client side search of routes / areas
- [ ] 'new' routes page, search by set date, setter etc
- [ ] gym node page, and every area page under gym renders the same data. basic gym node data (enough to link to manifest file and api call to get more data) and that's it
- [x] needs to sort http / https stuff, always server https? does this mean always serve QR code to secure url? - Yup:forced all QR codes into https version.

**Comment by rouletout** [comment]
obsolete, closing
