### ISSUE TITLE
Checklist for reviewing star schema data inadequacies

### ISSUE THREAD

**Issue by scd** [theCrag/website#1387]
There are a couple of issues with star schema data inconsistencies. This is a checklist of things to do to fix them. I am going through a more in-depth review of our current data, and as issues come up I will document them here:
- [x] merged nodes should have level set to 0
- [x] deleting annotations should have level set to 0
- [x] node sequence should be set to empty for merged nodes
- [x] node sequence should be set to empty for deleted nodes
- [x] node sequence should be set to empty for deleted annotations
- [x] merged nodes should not have ancestor collectors
- [x] merged routes/areas should have their record status set to 0
- [x] resequece page shows the wrong merged route - #1375 
- [x] algoritm bug for Nx fields when reparenting to a deeper level - #1384
