### ISSUE TITLE
Internal code refactor checklist

### ISSUE THREAD

**Issue by scd** [theCrag/website#1486]
There are some pieces of code which need refactoring for various backend efficiency reasons. This issue has been created as a checklist reminder for Simon to do at some stage:
- [x] Remove reliance of templates on database config entries. Improve backend productivity and allow hotfix creation of new templates.
- [x] URL processing. Standardise complex code bloat
- [x] Data preparation for templates. Removes duplication and ensures better standardisation of data presented to templates
- [ ] Replace automatically generated perl state modules with JSON config files. This will reduce code memory size
- [ ] Standardise all custom MySQL queries. Reduce code bloat and make SQL more maintainable.
- [ ] Rework login processing. Makes the code more understandable and reduce code duplication (ie same functions are implemented two different ways).
- [ ] Load system categories as a single SQL call into a JSON config file. Will reduce lots of small database queries to get category ids.

**Comment by scd** [comment]
THis can be done as part of our internal system maintenance. Closing from public facing.
