### ISSUE TITLE
Create a milestone release info page from github issues

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1586]
- [x] Some sort of static page generator which sucks up github issues for a particular release (or regen for all releases)
- [x] formats it nicely, either using our skin, or just into a form that gets plugged into our /article/ dir and picked up from there
- [x] needs to be aware of bugs vs enhancements vs new features. New features get a bigger blurb, possibly extracted from the issue description. Bugs just get a link to github issue
- [ ] generate a nice icon for each release for when we link to it from facebook etc
- [x] can exclude certain milestones
- [x] only works for milestones that are closed
- [x] for new features, include the issues description up to a -- marker
- [x] for improvements, see above
- [x] for bugs just show the name
- [ ] show 'missing' or poorly tagged issues in an 'other' category
- [ ] don't show headings if no issues in that heading
- [ ] parse links? swap to CragMarkdown? how to bootstrap the whole crag libs?
- [x] set user agent to 'thecrag'
- [x] set up api keys / username pass
- [ ] if tagged internal then ignore
- [ ] set facebook title to something nicer - fix article template somehow?
- [ ] set fb og image and description etc

There are a bunch of various open source scripts out there that do this, so mostly a bit of testing and mucking around.

As needed we can groom the issues to clean up the content that is pulled into these pages.

**Comment by scd** [comment]
can you do a post release hot fix and let me know the scripts that need to be run as part of the next release procedure - I need to add it to the release workflow.

**Comment by brendanheywood** [comment]
Probably more than a couple hours work so lets leave this for either a patch release in a week or two or the next release. Main to do items is getting the routing right and making a new release template.

**Comment by scd** [comment]
@scd to create a /releases/ template framework for brendan.

If I get time I will hot release this.

**Comment by scd** [comment]
I have just pushed to repo a release template associated with the '/release' url. I think this will give you what you want to complete the work.

**Comment by brendanheywood** [comment]
Ok this is at least ready for some beta testing and a soft release.

Step 1) Download the json from github and save locally

bheywood@cidsbrendan:~/CIDS/CIDS/application/content/releases-generator$ ./generate.pl

This ONLY does closed releases with the right naming convention, this should be after you close the release in github in your process. I would close the release, run the generator, see how it comes out and then probably do a few tweaks to make sure it looks right. One thing I really would like to see sorted is the og:image set for every release so it looks great when we promote it on facebook.

To make sure this works each release should have an image in it's description, github doesn't actually turn this into an image on github but my code will pick it up. Usually just cut and paste it from a screenshot that is in the most important issue in the release.

DO NOT TEST THE URL IN FACEBOOK to see how it looks in a preview. Once facebook scrape it it's really hard to refresh their cache, so instead preview the url inside their url linter and make sure it comes out look nice in the preview at the bottom.

https://developers.facebook.com/tools/debug/og/object/


Step 2) This then gets checked into git. These files don't change often and I've tried to strip out any lines which would could a diff if you re-run it. Generally only the newest release and the index should change but this can be improved if tags and other things change.

Step 3) Deployment, using ant 'ant rel' or you can rsync or whatever. See CIDS/application/frontend/build/build.xml for more

The templates are given the raw parsed json as template data and rendered on the fly from there.

**Comment by scd** [comment]
- [ ] http://dev.thecrag.com/release should open to the latest release by default
 - [x] it looks like everything after the '---' line in the milestone description is not propagated through to the release notes - this is cool.
 - [x] I have touched generate.pl to remove the exit and include a flag variable to stop it regenerating an existing file. I presume the exit was their for testing purposes.
 - [x] process works on simons dev
 - [ ] update release code, however will not be tested until next release
 - [ ] develop standards for documenting issues so they are clearer in the release notes.

**Comment by brendanheywood** [comment]
I was thinking /release would go to an index of all releases

**Comment by scd** [comment]
+1

**Comment by brendanheywood** [comment]
This is pretty solid now
