### ISSUE TITLE
Highlight milestone ascents in streams

### ISSUE THREAD

**Issue by scd** [theCrag/website#2028]
It would be pretty cool to highlight milestone ascents in the stream tick events. For example:

Campbell Gome went climbing in Arapiles ... He ticked his hardest onsight.

Some other ideas.
  - [ ] hardest by tick type and gear style
  - [ ] first onsight
  - [ ] hundredth route climbed

**Comment by scd** [comment]
This is way harder then I want to deal with right now. I cannot think of a simple query to get notable ascents and I am worried about the resource usage if we are doing this query live for every tick event.

I think we need a different approach which may be to flag an ascent as a notable ascent when it is logged and record the reason why it is a notable ascent.

The queries we devise for notable ascents will be acceptable for the logging process. If these queries are too slow then we could schedule the processing to happen soon after ascent is logged.

I think the important step is to record why it is a notable ascent. In this way the event stream just displays what has already been determined.

Tasks to complete this:
 - [ ] complete notable ascent queries - there may be multiple queries
 - [ ] we may have to record our internal grade somewhere close to the ascent so that we can do the hardest query across grading systems
 - [ ] determine if we also want to take into account the ascent AltGrade.
 - [ ] is logic based on ascents already logged (ie create date) or the ascent date. In otherwords do we try and take into account people back populating in non sequential order.
 - [ ] add a WhyNotable data field to ascent
 - [ ] schedule processing of notable ascents
 - [ ] assess if there are any cross impacts with other ascents in a tick event
 - [ ] display notable in streams
 - [ ] replace notable ascent logic in public profile page

I think is is a fairly cool and important feature, but too much work for now and there are other cool and important features to work through.

**Comment by scd** [comment]
For references I have done an experimental query on the server to play with this and get an output something like:

```
TickLabel	SystemLabel	Count	GradeLabel
tick	AU	1	29
tick	YDS	1	5.9
tick	BLDV	1	V7
onsight	AU	1	27
onsight	YDS	2	5.13a
onsight	FR	1	8a
onsight	FR_ALT	4	5
onsight	UIAA	1	8
flash	AU	2	27
flash	YDS	1	5.12d
flash	YDS_ALT	1	5.10+
flash	FR	2	7c
flash	UIAA	2	8-
redpoint	AU	2	29
redpoint	YDS	1	5.12b
redpoint	FR	2	7c
redpoint	FR_ALT	2	5
pinkpoint	AU	1	32
pinkpoint	YDS	2	5.13c
pinkpoint	FR	2	8a+
pinkpoint	UIAA	3	8
dog	AU	14	33
dog	YDS	7	5.13c
dog	FR	6	8b+
dog	UIAA	1	9-
second	AU	1	22
second	YDS	2	5.10a
second	FR	2	7a
second	FR_ALT	1	5+
secondclean	AU	1	28
secondclean	YDS	1	5.10a
secondclean	FR	1	6c+
secondrest	AU	1	25
solo	AU	1	25
solo	FR	2	7a+
solo	FR_ALT	1	4
toprope	AU	1	25
toprope	FR	2	6a+
topropeclean	AU	1	29
topropeclean	FR	1	6a
toproperest	AU	4	32
toproperest	FR	1	7a
aid	AU	1	22
aid	AUAID	1	M1
aid	AID	1	A3+
aidsolo	AID	2	A0
firstascent	AU	1	32
firstascent	FR	1	8a
firstascent	AID	1	A1
firstascent	BLDV	1	V4
ghost	AU	26	33
ghost	YDS	1	5.13d
ghost	FR	4	8b
ghost	UIAA	1	11
firstfreeascent	AU	1	32
attempt	AU	1	25
attempt	FR	1	7c+
working	AU	2	33
working	FR	1	8a
```

**Comment by brendanheywood** [comment]
How about a different approach, instead of a simple boolean flag we have an 'interestingness' stat for an ascent which we can generate using multiple signals and then just choose the top N for a given period. So signals could be a tick in a new crag, the grades std deviation from your normal grades, new tick types etc

**Comment by scd** [comment]
I think that is a third view and really useful. The particular use case this issue was looking at was which ascents in an event to show as priority and whether or not to highlight an achievement.

But I think you are right and my thinking is in line with your signals. We develop a pool of signals which can be used in different modes including home profile page, events and facet search, etc
