### ISSUE TITLE
http2 spdy tls rough checklist and implications

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2106]
> Whenever we want, don't we just turn on http2 on in apache in prod. I presume our version of apache supports this mod.

mod_spdy was super easy to setup on dev, http2 isn't so mature yet in apache or elsewhere
- [ ] This means we are committed to ssl across the site
- [x] 301 redirect all http traffic to https
- [ ] check / test any users of our api that will get redirected, make sure they correctly handle this and/or know it's coming
- [ ] audit tls setup so it's as efficient / secure as it can be:  https://httpsecurityreport.com/?report=www.thecrag.com and https://www.ssllabs.com/ssltest/analyze.html?d=thecrag.com&latest
- [ ] make sure newish browsers correctly use SPDY and brand new browsers use HTTP2 (this is one area I am hazy on, not sure if there are good apache mods that cover both specs) (there was talk of google working with apache to make this core on 2.6 or 3.0 but can't find solid evidence of this)
- [ ]  consider swapping the first layer of routing end from apache to nginx which has stronger spdy and appears to be moving quicker towards http2, so nginx would do routing and ssl termination, then reverse proxy to apache / thumbor (this has other benefits too like much more efficient connection handling)
 - [ ] fop does not work with https css files. This means pdfs will not work if we force https. We need to work out why fop is broken, or work on a new PDF pipeline

**Comment by scd** [comment]
There are a few things to do here. Not very good on the first of the security reports. Maybe we should list the items we want to pass before proceeding. I redid the report with https as it got a zero mark with just the domain name.

https://httpsecurityreport.com/?report=https://www.thecrag.com

I am happy with the nginx proposition.

I think we are the biggest user of our own API. Off the top of my head the API users we need to consider:
  * Our own website;
  * Nicky's Wordpress but plugin;
  * Stripe has some callbacks registered - make sure they are https  

We should instruct all future users to use https for the API. Maybe we should do a trial for a month by restricting the API to https.

**Comment by brendanheywood** [comment]
Yeah they are just rough guides, we need to think about each one and not blindly follow it. eg 'Subresource Integrity' is still an emerging spec and I wouldn't consider it stable yet. I actually helped the guy who runs that site fix a bug in his tests the other day which meant the testing page wouldn't run in an older chrome because of changes in the SRI spec - ironic huh :)

Others like frame options we want to explicitly allow for embedding. Others like key pins are a good thing, but you have to be very careful as if you screw it up you can bring down the site and there is almost no way to fix it because it will look to a browser like your site has been compromised.

> We should instruct all future users to use https for the API.

http is dying, and faster than you may think. Browsers are starting to auto swap to https silently if it's available. You should read this:

https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/

and this from Sir Tim is pretty interesting too:

http://www.w3.org/DesignIssues/Security-NotTheS.html

**Comment by scd** [comment]
Closing as this is managed internally.
