### ISSUE TITLE
Significant works task list for internationalisation

### ISSUE THREAD

**Issue by scd** [theCrag/website#2231]
- [x] translations framework - #2208
- [ ] url encoding - #1306 
- [ ] area/route description translations 
- [ ] port articles to nodes with an article node type
- [x] translations in javascript - #2251
- [x] terms and conditions workflow and translation key schema - #2236
- [ ] template keys - partially done
- [ ] system database config keys - partially done
- [ ] mobile app keys
- [x] welcome message
- [x] update t&c
- [x] emails encoding - #2237 
- [x] account language selection
- [ ] remove after content in css (eg login button uses 'or' as after text in the css). 
- [ ] remove english from javascript, call translator
- [ ] translations for area and route descriptions
- [ ] site articles

**Comment by scd** [comment]
Current prioritisation of work to for the first release
 - [x] selection of framework
 - [x] translation keys for home page and signup page
 - [x] translation keys for site policies
 - [ ] translation keys for emails
 - [ ] email language logic (eg different welcome message crag)
 - [ ] keep language selection from home page to signup page. Is this via session management or parameters on links
 - [ ] account language selection in profile
 - [ ] dashboard keys
 - [ ] area page template keys
 - [ ] route page template keys
 - [ ] log ascent keys
 - [ ] stream keys
 - [ ] url scheme change

**Comment by scd** [comment]
Processes that need translation:
 - [ ] upload photo
 - [ ] view karma
 - [ ] donate
 - [ ]

**Comment by Mdemaillard** [comment]
- [ ] Title Page #2309 
- [ ] diverses #2385

**Comment by rouletout** [comment]
Most of this is actually done or split into individual cards or issues, closing.
