### ISSUE TITLE
Show grading system and grade conversion on mouseover and / or convert all grades to local system

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2245]
It would be nice to get a popup showing the used grade system in the route's listing of a crag (on a mouseover on the grade button) . Sometimes it is not obvious, for example UIAA and FR_ALT grades in the Alps, and most users won't know the grade context logics by hard.

Tasks:
* [ ] refactor all grade into atomGrade, convert grade template to new bem / css (also #2419)
* [ ] have a context query param for quick preview of converting all grades #2540
* [ ] have a user preference for either auto or which context to use #2527
* [ ] review all grade systems to ensure translation is correct #2557 / #2278

**Comment by brendanheywood** [comment]
+1 from @Basti-muc

**Comment by brendanheywood** [comment]
+1 from @rouletout

**Comment by brendanheywood** [comment]
cross link to https://github.com/theCrag/website/issues/2527

**Comment by brendanheywood** [comment]
Some relationship with https://github.com/theCrag/website/issues/1118

ie if we convert and cross a grade boundary which grade band do we show, original or converted?

**Comment by brendanheywood** [comment]
> ie if we convert and cross a grade boundary which grade band do we show, original or converted?

Answer: cpr grade which is always the same regardless

**Comment by quaestor** [comment]
Plus one from me, especially the part discussed in #2775.

**Comment by rouletout** [comment]
+1 - if we want to to display "global" lists like the world's hardest routes or similar we need to be able to convert them to a "user defined" grading system. 

E.g. https://www.thecrag.com/climbing/world/routes/?sortby=grade,desc

**Comment by brendanheywood** [comment]
+1 from support

**Comment by Mdemaillard** [comment]
Candidate for closure after Release 81 ?

**Comment by lordyavin** [comment]
Please check the todos which are done.
