### ISSUE TITLE
sandpit todo

### ISSUE THREAD

**Issue by scd** [theCrag/website#2478]
- [x] add test server, data will be lost warning to the UI
 - [ ] turn off data will be lost warning for translate page
 - [ ] uploading photo should not trigger sync with static
 - [ ] confirm local thumbor working
 - [ ] ssl check: https://www.ssllabs.com/ssltest/analyze.html?d=sandpit.thecrag.com&latest
 - [ ] add ssl check to documentation
 - [ ] work out why forward secrecy is not working on sandpit
 - [ ] application server and only application server should work

**Comment by Mdemaillard** [comment]
was that initial setup of sandpit server ? still valid ?

**Comment by scd** [comment]
I am just going to close this as the sandpit setup is finished. We are working with some of these issues not done.
