### ISSUE TITLE
Checklist of cpr timeline chart features

### ISSUE THREAD

**Issue by scd** [theCrag/website#2636]
@brendanheywood I am creating this issue as a final checklist of cpr timeline chart features.
 - [x] Use template data for labels: they are translated
 - [x] Use template data for chart title (also translated)
 - [x] Use template data to decide on cpr curves to be displayed. Use simple algorithm for now, we can make improvements later.
 - [x] Add Current Rating to chart - in template data
 - [ ] Add watermarks to chart (in template data)
 - [ ] Make sure a blank chart does not look confusing
 - [ ] Graph with cpr in only one time slice
 - [x] choose color for top rope curce so it's not the same as cpr (black)

**Comment by brendanheywood** [comment]
Ok so I think 'curvePriorities' needs to be adjusted to only show the curves that we want for each gear type. ie for bouldering graphs we need to decide what to show, and what to call them. I think we for bouldering we completely ditch red and pink, top rope and second, and create a brand new one called 'sendCpr' which is just almost everything else. Even a bland 'tick' for a boulder I think we can safely assume is a proper send with a boulder which we cannot assume for a route (you can't second, dog, aid or whatever)

![image](https://cloud.githubusercontent.com/assets/187449/23775348/67feeef4-057c-11e7-9c2a-3d5f16ea638c.png)

Also even for a sport route, the priorities above seems slightly off to me. If I was to flash something, then don't red and pinkpoint both include flash in their stats? Which means they will automatically be at least as high as flash which means that the flash curve will never ever be visible? So either we need the curve priorities to be consistent with the nested super sets of tick types, or we should just completely ignore flashCpr and remove it. I think given flash in most cases is going to be very close to at least 1 of the other curves it isn't adding a lot of value and we could ditch it.

Also I think most beginners are more likely to top rope a route before they second one, so I think top rope should be the lowest priority? Seconding can be quite hard removing gear so it technically harder than a simple top rope.

And obviously if a curve is removed from the priorities it is also removed from the timeSeries as well.

So this is my suggested priorities:

Sport:

"name": "onsightCpr",
"name": "redpointCpr",
"name": "pinkpointCpr",
"name": "secondCpr", <-- keep OR combine with top rope?
"name": "topropeCpr",

Trad priorities:

"name": "onsightCpr",
"name": "redpointCpr",
"name": "pinkpointCpr",
"name": "secondCpr",
"name": "topropeCpr",

Boulder priorities:

"name": "onsightCpr",
"name": "flashCpr",
"name": "sendCpr",

**Comment by brendanheywood** [comment]
Legend is translated

![image](https://cloud.githubusercontent.com/assets/187449/23777060/2e6f085e-0586-11e7-9ecc-e65d7ccf1c23.png)

**Comment by scd** [comment]
I have fixed this so that the curve priorities are largely fixed dependent on the style as per @brendanheywood recommendations. Let's see how this goes.

the graph now gets it's info from the curvePriorities template parameter.

**Comment by brendanheywood** [comment]
I've added your current cpr number:

![image](https://cloud.githubusercontent.com/assets/187449/24080008/c87faf9c-0ce9-11e7-9305-ee338c39a949.png)

but if it has sufficiently decayed then you get the last proper one as well:

![image](https://cloud.githubusercontent.com/assets/187449/24080011/df6639d8-0ce9-11e7-8506-b2012955b66e.png)

**Comment by brendanheywood** [comment]
fixed top ropecolor:

![image](https://cloud.githubusercontent.com/assets/187449/24081043/3e5b2164-0cff-11e7-9056-f7fa9789d655.png)

**Comment by brendanheywood** [comment]
@scd what exactly did you want with the water mark?

Can you also provide some examples which look bad for:

* Make sure a blank chart does not look confusing
* Graph with cpr in only one time slice

**Comment by scd** [comment]
> @scd what exactly did you want with the water mark?

Subtle opaque text over the chart. We don't need it for our own embeds, but when we are embedding on external sites it should be on by default. This is not a blocking issue for the the release so leave it for now.

> Make sure a blank chart does not look confusing

For this I created a new account and this is what the chart looks like:

![cpr-new-account](https://cloud.githubusercontent.com/assets/373058/24085173/14f2a076-0d4b-11e7-85ee-c9dc8780fe83.png)

The yaxis has got some funny behaviour when there are no ascents.

 > Graph with cpr in only one time slice

Hmmm, i will have to get back to you on this one. It is fine if there is one historical ascent, but when there is one recent ascent there is nothing displayed. Irritatingly, I missed a step when rebuilding dev so we still cannot log an ascent on dev to go through this failure case.

**Comment by scd** [comment]
> Graph with cpr in only one time slice

https://dev.thecrag.com/climber/scd_test

![cpr-single-recent-ascent](https://cloud.githubusercontent.com/assets/373058/24090411/0723c03a-0d94-11e7-9657-a32ba59312c3.png)

But here is a different example of a single ascent from the past, which seems fine:

https://dev.thecrag.com//climber/bluebell

![cpr-single-old-ascent](https://cloud.githubusercontent.com/assets/373058/24090504/ed4e60e2-0d94-11e7-8171-d98d2f6857f1.png)

**Comment by scd** [comment]
On lee's timeline we now have a green rating. I don't think we should display rating numbers for individual tick types. There is already an all time CPR, current CPR, recent CPR (and potentially peak CPR). This is the only place a green rating is displayed, but the black rating is used in rankings. 

http://dev.thecrag.com/ascents/aggregate/graph-sport-cpr/with-route-gear-style/sport/by/leecujes/

![cpr-timeline-green-rating](https://cloud.githubusercontent.com/assets/373058/24171914/6f06859c-0eda-11e7-9bcb-c8bb842731b8.png)

**Comment by brendanheywood** [comment]
No we don't, that not green it's gray and is the decayed current cpr. It has happens to sit over the green curve in this particular chart

**Comment by scd** [comment]
wow, my eyes are not very good anymore :)

**Comment by brendanheywood** [comment]
but it's still a fair point, I'll try and tie the number(s) to the right point(s) in a stronger way

**Comment by scd** [comment]
@brendanheywood if you have finished everything from here from the release then can you please close this issue, listing outstanding stuff in their own issue.

**Comment by brendanheywood** [comment]
yup closing
