### ISSUE TITLE
Reparenting stream activity

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2697]
**What happened?**

Key '{to}' issue with stream activity when reparenting child

Example:
[https://www.thecrag.com/climbing/italy/dolomites/rosengarten-the-vajolet-towers/area/1207383570](url)

> Added reparented child 'Delago Tower/South West Arete"Delagokante"' to '{to}’.

**What you expected:**

> Added reparented child 'Delago Tower/South West Arete"Delagokante"' to 'Torre Delago'.

**Comment by lordyavin** [comment]
This is bugging me a long time. For unknown reasons the {to} placeholder is not replaced with the name of the new parent. I suppose it is simply not implemented and IMHO it isn't necessary to add the parent name because it is displayed below the information that the parent is updated:
![grafik](https://user-images.githubusercontent.com/1528540/37758256-d8a18552-2daf-11e8-9fb2-666144e91486.png)
So it would be sufficient to state that a new child was added.

But there is another issue. It isn't stated what the original parent was. This could be of use if reviewing this event. Additionally the update event of the original parent is quite useless:
![grafik](https://user-images.githubusercontent.com/1528540/37758401-5c0c9936-2db0-11e8-842a-dd1fa811e64b.png)
Displaying the full stream event doesn't reveal any further details but it should state that a child was (re-)moved to another node.

**Comment by lordyavin** [comment]
And hey guys I think this issue needs some attention. I wonder why nobody else is complaining.

**Comment by scd** [comment]
This is a multi-facetted issues, which I only propose to investigate and fix the missing `{to}`. The tasks on this event are:

  - [ ] investigate why the `{to}` is missing from the `template.stream.detail.added-reparented-child` in template `stream/event-update-item-detail`.
  - [ ] investigate whether `areaType` data is available in the stream, if not add it
  - [ ] investigate whether `oldParent` data is available in the stream
  - [ ] discuss changing the stream text.

Note that it looks like the `{to}` field data should be there, so something is broken or missing somewhere.

**Comment by scd** [comment]
Notes for debugging. Here is the stream event

https://www.thecrag.com/event/1207314336

and on simons' dev

https://192.168.56.2/event/1207314336

**Comment by scd** [comment]
The bug here was referring to `to` when it should have been referring to `from`.

Fixed on Simon's dev. This is what it will look like.

![screenshot from 2018-03-27 15-45-53](https://user-images.githubusercontent.com/373058/37947308-167d5de0-31d6-11e8-97b9-082a589a082b.png)

**Comment by rouletout** [comment]
solved, closing
