### ISSUE TITLE
Various tick types missing from graph on route page

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#271]
Look at piechart:

http://www.thecrag.com/route/120148635

It has 1/3 pink and 2/3 dog.

It doesn't include Lee's FA clean ascent?

So the tick type bar chart should be raw tick type, not groups. The data should be exactly equivalent to what you see on this facet page:

https://www.thecrag.com/climbing/australia/mt-coolum/route/120148635/ascents?sortby=tick-type,desc

**Tasks**
* [x] Show full list of all tick types
* [x] re-map certain tick types, eg FFA -> Red point
* [x] link each bar to the correct facet drill down

**Comment by brendanheywood** [comment]
Just reviewed this one and it's progressively gotten worse as we've added more tick types. We need some broad approach here so that this pie chart just picks up new tick types as they are added. I think we should just simplify the logic here and apart from excluding the target / working tick types, we should just include absolutely everything.

eg 24 ascents:

https://www.thecrag.com/climbing/australia/grampians/ne-mt-zero-range/route/17629609/ascents

but only 18 are shown, this is missing the new 'All free' type

https://www.thecrag.com/climbing/australia/grampians/ne-mt-zero-range/route/17629609

![image](https://user-images.githubusercontent.com/187449/29491892-6359e672-85ad-11e7-935c-3cb0e8a38633.png)

**Comment by brendanheywood** [comment]
Just re-tested for good measure, the chart has been converted to a bar chart but the data bug is the same, there is lots of tick types missing or not grouped the way we want.

I think the specific fix here is very simple and all we need is to map the FA tick type to the tick group and we can close this. This is an issue is the stored stats not the display

**Comment by brendanheywood** [comment]
Moving this to the next release, half the work for this is done, but just need to apply the same consistent logic (tick mappings) from the profile notable ascents and pyramids to this data.

**Comment by scd** [comment]
This is now done. Rather than use the stored stats I calling the actual facet. This means the numbers are far more likely to align. 

![screenshot from 2018-10-08 18-33-27](https://user-images.githubusercontent.com/373058/46596553-bcb66300-cb28-11e8-807b-69f9ccb7a08c.png)

![screenshot from 2018-10-08 18-33-21](https://user-images.githubusercontent.com/373058/46596557-c213ad80-cb28-11e8-95e2-ddbddf3d7bc8.png)

**Comment by brendanheywood** [comment]
Cool, can you please order these by cleanness / cpr tick shift instead of popularity? This can probably reuse the same orderings as the pyramid label order

**Comment by brendanheywood** [comment]
Perfect :)
