### ISSUE TITLE
Gym action menu items for managing permissions inconsistent

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3107]
There is/was a translation error for the sub menu item to review the permissions of a gym.

![grafik](https://user-images.githubusercontent.com/1528540/37098974-84a54e70-221f-11e8-8031-4d044697a11a.png)

I checked the keys
* template.action-area.update-permissions-area-type
* template.action-area.review-permissions-area-type

and corrected template.action-area.review-permissions-area-type for German to contain the same variable as the English text. But I wondered why one key is using {areaName} and the other one {areaType}. What is it supposed to be?

-------------------------------------------------
**TODO**
> Most items should be 1 or 2 words like 'Update permissions' instead of 'Update Ebor Falls permissions'. I would say that most menu items should not contain either the node title or the node type.

* [ ] default (en)
* [x] de
* [ ] es
* [ ] fr
* [ ] it
* [ ] ja (yet not translated)
* [ ] ja (yet not translated)
* [ ] ko (variable is written in korean too)
* [ ] tr (yet not translated)
* [ ] zh_HANS (yet not translated)
* [ ] zh_HANT (yet not translated)

**Comment by rouletout** [comment]
It should be {areaName} to show "Kletterwerk as in the item above. This was changed to avoid "language" issues with e.g. different articles required in other languages. If we put the name it is always correct.

**Comment by lordyavin** [comment]
Why not omitting the name/type as in the items above?

**Comment by scd** [comment]
It is meant to be the English version

**Comment by scd** [comment]
I think we should try and shorten them without the names because having the variable menu width is causing issues. 

Does areaType not make sense?

Keep this issue open because I really want to get rid of all references to the area names in the action menu.

**Comment by scd** [comment]
There are other issues as well, like when I am explaining what to do, I have to go to the menu to work out what the menu says because it is different for every area. I am happy for you to treat the menu width thing separately. Just be aware I still want to simplify the menu.

**Comment by brendanheywood** [comment]
Yeah I would be in favor of selecting phasing out the use of the crag node type in places like this so it's consistent. Most items should be 1 or 2 words like 'Update permissions' instead of 'Update Ebor Falls permissions'. I would say that most menu items should not contain either the node title or the node type.

**Comment by lordyavin** [comment]
I updated the german translation according to brendan. Following languages left:
* [ ] default (en)
* [ ] es
* [ ] fr
* [ ] it
* [ ] ja (yet not translated)
* [ ] ja (yet not translated)
* [ ] ko (variable is written in korean too)
* [ ] tr (yet not translated)
* [ ] zh_HANS (yet not translated)
* [ ] zh_HANT (yet not translated)

**Comment by rouletout** [comment]
This looks like fixed to me - I'm closing this.
