### ISSUE TITLE
Node merging how-to

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3505]
**What happened?**
Other users asked me how to move and merge routes. There is no help article that explains how to do it. the existing article is by design no tutorial or how-to: https://www.thecrag.com/de/artikel/merging

**What you expected:**
* [ ] A step by step how-to with screenshots for moving nodes
* [ ] A step by step how-to with screenshots for merging nodes
* [ ] Change title of existing article https://www.thecrag.com/de/artikel/merging

**Comment by lordyavin** [comment]
What I wrote to an user so far:

---------------------------

**Verschieben**

Über das "Aktions" Menü des Gebiets, Sektors (drei punkte neben "Felswandbearbeiten)

* Gebiet/Sektor/Felswand neuer Mutter zuweisen
* Auswahl "Reparent children of selected node"
* weiter
* Auswahl der Route
* weiter
* Im nächsten Formular kannst du das Ziel direkt auswählen ("Select New Parent") oder das Zielgebiet ändern ("Change Area"). Wir nehmen mal den einfachen Fall an und eines der Dropdownfelder enthält den Knoten den du haben möchtest. Also diesen auswählen und "Select New Parent" setzten.
* weiter
* Dann noch den Einfügepunkt wählen (Insert Before) und bestätigen (Confirm Reparent).

**Routen Zusammenführen**

Hier gibt es zwei Möglichkeiten:
1. Wenn die Routen bereits im gleichen Knoten liegen kann man sie in der Liste beide selektieren oder über das Kontextmenü zusammenführen.
2. oder über das Aktionsmenü er Route ("Action" rechts neben "Edit Route" -&gt; Restructure -&gt; "Merge Route")

Hier gibt es auch die Auswahl "Reparent Route" was das gleiche macht wie zuvor beschrieben.

---------------------------

**Move**

Via the "action" menu of the area or sector (three points next to "edit area")

* Assign area/sector/cliff to new mother
* "Reparent children of selected node" selection
* Next
* Route selection
* Next
* In the next form you can select the destination directly ("Select New Parent") or change the destination area ("Change Area"). Let's assume the simple case and one of the drop down boxes contains the node you want. So select it and set "Select New Parent".
* Next
* Then select the insertion point (Insert Before) and confirm ("Confirm Reparent").

**Merge Routes**

There are two possibilities here:
1. If the routes are already in the same node, you can select them from the list or merge them via the context menu.
2. or via the action menu Route ("Action" to the right of "Edit Route" -&gt; Restructure -&gt; "Merge Route")

Here you can also select "Reparent Route" which does the same as described before.

**Comment by Mdemaillard** [comment]
Additional note: i have use both move and merge a few times by now. When merging 2 routes, i find it still very difficult to identify which of the 2 routes will "stay" and which will "disappear". As a result, 50% of the time i have then to reorder or move the "staying" route to the correct place.

What i expect: during the merge UI, clearer message on which node ("disappearing") will be merged into which node ("staying").

**Comment by matozoid** [comment]
Now that you're in the neighborhood: "...select the destination directly ("Select New Parent") or change the destination area ("Change Area")..."

For a long time I didn't know what to choose. The options didn't make sense since they meant more or less the same to me.

**Comment by Mdemaillard** [comment]
+1 to Matozoid. "Change Area" may be reworded somehow with "Navigate to different area"

**Comment by scd** [comment]
I think that I can close this after the last release.
