### ISSUE TITLE
Add "meta" forum sections like website, gear etc.

### ISSUE THREAD

**Issue by georg-d** [theCrag/website#3669]
**What happened?**
In top navigation, section "forum" shows World, Germany, Gyms, releases etc. and after clicking "World", the left hand navigation offers different regions, Virtual and test area. As a user, I had no idea where to place questions or start discussions about website itself (so a meta discussion), e.g. the meanings of the different "Point types" in Topos. Similar for other discussions not related to a locality but e.g. gear, security/safety,...

**What you expected:**
* [ ] Add "Virtual" into list that unfolds on mouse over top navigation point "Forum"
* [ ] Within "World", move "Virtual" to the top so it's 1st parant
* [ ] Within "Virtual", add "theCrag website", "gear", "security" and potentially further sections.
* [ ] Within "World", show the already existing forums "release" and "gyms" and "tagging" because these cannot be reached when you're within one of the other forums

**Comment by Mdemaillard** [comment]
related to #2745

**Comment by georg-d** [comment]
To my understanding both are related but not the same: #2745 is about categorization/typing of forum posts wherever in the forums hierarchy they are, #3669 is about changing forums hierarchy.

**Comment by Mdemaillard** [comment]
correct, which is why i didnt mark as duplicate and closed it :-) i link related / similar issues so that the devs can tackle multiple issues in one dev effort, if possible.

**Comment by Mdemaillard** [comment]
Also to consider in parallel: scope of search function, and mean of navigating while searching.
 
Currently it is somehow difficult to do a search in the release forum, because in a common user case the search is initiated while in a session having been somewhere in the world index. (crag, country, whatever). The search when used, even after going into "conversation" search, and extending the scope on "world", still exclude theses forums which are not under World. 
I find it actually quite convoluted to manage to "extend" the search scope beyond World.
